networks:
  rate-network:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rate-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - rate-network

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-keycloak-schema.sql:/docker-entrypoint-initdb.d/create-keycloak-schema.sql
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rates
    networks:
      - rate-network

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: rates
      DB_SCHEMA: keycloak
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    networks:
      - rate-network

volumes:
  postgres-data: