DROP TABLE IF EXISTS rate;
DROP SEQUENCE IF EXISTS rate_seq;

CREATE SEQUENCE IF NOT EXISTS rate_seq START WITH 100000 INCREMENT BY 1;

CREATE TABLE rate
(
    id            int8           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sell_rate     numeric(15, 6)                                  NOT NULL,
    sell_iso      varchar(255)                                    NOT NULL,
    sell_code     int4                                            NOT NULL,
    buy_rate      numeric(15, 6)                                  NOT NULL,
    buy_iso       varchar(255)                                    NOT NULL,
    buy_code      int4                                            NOT NULL,
    quantity      int4                                            NOT NULL,
    currency_name varchar(255),
    rate_date     timestamp                                       NOT NULL
);
